version: "3.8"
   
services:
  web:
    build: .
    command: >
        sh -c "python3 manage.py makemigrations &&
               python3 manage.py migrate &&
               python3 manage.py loaddata questions.json &&
               python3 manage.py loaddata choices.json &&
               python3 manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
